### ISSUE TITLE
error while installing cdncheck

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/pdtm#148]
### pdtm version:

```
$ pdtm --version
[INF] Current Version: v0.0.6
```

### Current Behavior:

Hello,

An error occurs when installing cdncheck.

Thanks.

### Steps To Reproduce:

```
pdtm -install-all

....
...
[INF] installing cdncheck...
[ERR] error while installing cdncheck: could not find release asset for your platform (linux/amd64)

```

![image](https://github.com/projectdiscovery/pdtm/assets/29292618/0c04c9e7-0a15-477a-b8d9-22ecc0daa452)

**Comment by ShubhamRasal** [comment]
related https://github.com/projectdiscovery/cdncheck/issues/103

**Comment by ehsandeep** [comment]
Closing this as duplicate, as it's being tracked at https://github.com/projectdiscovery/cdncheck/issues/103
