### ISSUE TITLE
Updating when an asset isn't available causes an uninstall

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/pdtm#149]
### pdtm version:
`v0.0.7`

### Current Behavior:
Currently there is an issue with `cdncheck`'s latest release not having any assets available (see https://github.com/projectdiscovery/cdncheck/issues/103).

In this state, PDTM knows that there is an update available for cdncheck, but when it goes to do an update, it deletes `cdncheck` and then cannot get the latest asset and thus leaves you without the tool after the "update"

<img width="1232" alt="CleanShot 2023-05-25 at 15 14 39@2x" src="https://github.com/projectdiscovery/pdtm/assets/6044920/f740b8a7-0214-4458-8f15-8c52ae3c35fd">

<img width="991" alt="CleanShot 2023-05-25 at 15 16 30@2x" src="https://github.com/projectdiscovery/pdtm/assets/6044920/58880994-0407-4157-9acc-c3298a666195">

<img width="173" alt="CleanShot 2023-05-25 at 15 16 39" src="https://github.com/projectdiscovery/pdtm/assets/6044920/f3af649d-3cfb-48b2-9ef5-4414b7a11e39">

### Expected Behavior:
When the update isn't actually available, leave the system in the same state instead of removing the tool. This could mean that a GitHub downtime or similar odd problem could screw up a lot of folks tools.

### Steps To Reproduce:
- Install cdncheck into the `pdtm` bin
  - To do this after mine was broken I did this
  - `wget https://github.com/projectdiscovery/cdncheck/releases/download/v1.0.3/cdncheck_1.0.3_linux_amd64.zip`
  - `unzip cdncheck_1.0.3_linux_amd64.zip`
  - mv ./cdncheck ~/.pdtm/go/bin/
- `which cdncheck` returns `/home/kali/.pdtm/go/bin/cdncheck`
- Observe the need for an update with `pdtm`
  - `21. cdncheck (outdated) (1.0.3) ➡ (1.0.5)`
- Run `pdtm -update-all`
- Observe the error above
- `which cdncheck` returns `cdncheck not found`
- cdncheck is now no longer in `/home/kali/.pdtm`
 
<img width="916" alt="CleanShot 2023-05-25 at 15 21 13@2x" src="https://github.com/projectdiscovery/pdtm/assets/6044920/2baf6cce-bac8-4cec-bec4-cee6b1d8c0f7">

**Comment by ehsandeep** [comment]
This is now fixed in latest release.
