### ISSUE TITLE
Not showing installed tools

### ISSUE THREAD

**Issue by tmgbiswadp** [projectdiscovery/pdtm#195]
### pdtm version:
0.0.8

### Current Behavior:
+ The 0.0.8 version does not list already installed tools

### Steps To Reproduce:
1. Run pdtm
2. See the list of tools and its status. 

![image](https://github.com/projectdiscovery/pdtm/assets/37303430/40a3044a-16b5-4493-adcb-0504deadb7af)

**Comment by tmgbiswadp** [comment]
@dogancanbakir,
What might be the cause for this. I haven't changed anything in my installation. Still its only showing nuclei as installed however on using -ua flag it updates all the tools.


<img width="749" alt="Screenshot 2023-09-13 at 23 51 12" src="https://github.com/projectdiscovery/pdtm/assets/37303430/2c2b539a-9fae-4f0d-b500-4dcaa671570b">

Regards

**Comment by tmgbiswadp** [comment]
@dogancanbakir,
Did not work.

<img width="742" alt="Screenshot 2023-09-15 at 00 45 52" src="https://github.com/projectdiscovery/pdtm/assets/37303430/bb23a4b4-2a21-49c9-adb6-ed53e3b2c8c1">

**Comment by dogancanbakir** [comment]
@tmgbiswadp,
Unfortunately, we were unable to replicate the same scenario. However, I have created a new branch to log some information that could assist us in debugging the issue. Could you test this branch and share the log with us? I appreciate your help.
Branch: [add_log_for_pr_195](https://github.com/projectdiscovery/pdtm/tree/add_log_for_pr_195)

Steps to follow:
```console
git clone https://github.com/projectdiscovery/pdtm.git
git checkout add_log_for_pr_195
cd pdtm/cmd/pdtm
go run .
```

**Comment by tmgbiswadp** [comment]
@dogancanbakir,
+ This was the response after following the steps:-

<img width="737" alt="Screenshot 2023-09-30 at 12 45 05 PM" src="https://github.com/projectdiscovery/pdtm/assets/37303430/e886373d-f13b-4fcd-809a-3257ac40dec7">

+ I have these tools installed in my machine:-

<img width="1512" alt="Screenshot 2023-09-30 at 12 46 37 PM" src="https://github.com/projectdiscovery/pdtm/assets/37303430/61c63fd1-dd89-4a07-9f17-d2c505236af2">

**Comment by tmgbiswadp** [comment]
@dogancanbakir,
+ So the only difference I am seeing between nuclei and other tools is that it has some kind of attribute set on it. 

<img width="630" alt="Screenshot 2023-09-30 at 1 13 19 PM" src="https://github.com/projectdiscovery/pdtm/assets/37303430/2b233c16-bfd7-4717-926e-a9e53ecb2a60">

**Comment by dogancanbakir** [comment]
@tmgbiswadp,
I appreciate your assistance and patience with this intriguing case. I couldn't locate any attribute on my machine. However, I'm curious to know the outcome if you execute the command `/Users/vapour/.pdtm/go/bin/katana --version` as this is how we usually obtain the version, and I don't see this in your output. See the lines that contain only `cmd run output:`.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue continues.
