### ISSUE TITLE
Naabu Installing via PDTM-Install-all

### ISSUE THREAD

**Issue by Done461** [projectdiscovery/pdtm#200]
![image](https://github.com/projectdiscovery/pdtm/assets/52113967/de594c41-466e-4040-80a9-c37d948f1487)
am trying to install naabu via pdtm 
this error shows although am sure its installed
i deleted pdtm and reinstalled same issue 
![image](https://github.com/projectdiscovery/pdtm/assets/52113967/4ba702f0-7930-4b21-b477-9e7fa7839108)

**Comment by Mzack9999** [comment]
@Done461 This is not an error message but a warning that reminds the user about tools requirements. You can ignore it if `libpcap` is already installed
