### ISSUE TITLE
minisign doesn't install correctly when running go install of latest build

### ISSUE THREAD

**Issue by STJS0** [projectdiscovery/pdtm#227]
https://github.com/projectdiscovery/pdtm/blob/37c342ea46eaf33a392ff96c36f13de66fea2c48/go.mod#L17

The go.mod file has the location set to haead.dev/minisign which is a dead link as of today. 
It should be github.com/aead/minisign/ or else you will get an error when you install via go

Steps and error:
$ go install -v github.com/projectdiscovery/pdtm/cmd/pdtm@latest
go: downloading aead.dev/minisign v0.2.0
go/pkg/mod/github.com/minio/selfupdate@v0.6.0/minisign.go:8:2: unrecognized import path "aead.dev/minisign": reading https://aead.dev/minisign?go-get=1: 404 Not Found

**Comment by dogancanbakir** [comment]
@STJS0, See https://github.com/projectdiscovery/subfinder/issues/1055. Closing this.
