### ISSUE TITLE
Installing or upgrading httpx to v1.6.1 does not work

### ISSUE THREAD

**Issue by inifares23lab** [projectdiscovery/pdtm#282]
### pdtm version:

v0.0.9

### Current Behavior:

Updating httpx from 1.6.0 to 1.6.1 or installing httpx does not work.
The upgraded or installed version remains 1.6.0 despite what the installation/upgrade process states (1.6.1).

### Expected Behavior:

Installing or upgrading to version 1.6.1 works.

### Steps To Reproduce:

1. Run pdtm -i httpx # or pdtm -u httpx or pdtm -ua
2. see outcome `[INF] installed httpx 1.6.1 (latest)`
3. Run httpx -version
4. see older version `[INF] Current Version: v1.6.0`

### Anything else:

```
pdtm -i httpx # "pdtm -u httpx" and "pdtm -ua" lead to the same result
[INF] installed httpx 1.6.1 (latest)
$
httpx --version

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current Version: v1.6.0
```

**Comment by dogancanbakir** [comment]
There is a minor issue with the versioning, which will be fixed in the upcoming release. You probably have the latest version. See https://github.com/projectdiscovery/httpx/issues/1716.
