### ISSUE TITLE
[FTL] Could not run pdtm: pdtm api is down, please try again later

### ISSUE THREAD

**Issue by MandemSec** [projectdiscovery/pdtm#328]
[FTL] Could not run pdtm: pdtm api is down, please try again later

**Comment by dogancanbakir** [comment]
Done, under Micro APIs https://status.projectdiscovery.io
<img width="945" alt="image" src="https://github.com/user-attachments/assets/ae2f99b8-3d1f-447e-af34-171c0a1ebc4f">
