### ISSUE TITLE
Output the currently installed versions

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/pdtm#34]
### Please describe your feature request:
Add a flag to print the currently installed versions of all the tools

### Describe the use case of this feature:
Maybe I just want to check which tools are installed / which versions of the tools before deciding to install a new one / install all

**Comment by ehsandeep** [comment]
@olearycrew there is PR from @edoardottt to include version in output https://github.com/projectdiscovery/pdtm/pull/42, do you have any feedback for CLI UI?
