### ISSUE TITLE
Doesn't appear to work with interactsh

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/pdtm#39]
### pdtm version:
v0.0.1

### Current Behavior:
When running on `linux/amd64`, you get these errors when running `-install-all`

```
[INF] installing interactsh-server...
[ERR] error while installing interactsh-server: could not find release asset for your platform (linux/amd64)
[INF] installing interactsh-client...
[ERR] error while installing interactsh-client: could not find release asset for your platform (linux/amd64)
```

### Expected Behavior:
Installs interactsh-server and -client

### Steps To Reproduce:
1. Install pdtm on a machine with linux/amd64 architecture
2. Run `pdtm -install-all`
3. Observe behavior.

### Anything else:
My theory looking at the code is that it's because the `linux` for both `interact-client` and `interact-server` has a capital `L` in the asset name.

Making the checks for this case-insensitive or re-realeasing those two packages to conform to the formatting the rest of the tools follow should solve this issue.

**Comment by olearycrew** [comment]
Note: if I'm correct about this, I think it will fail on Windows too for the same problem...though I don't have access to a Windows PC to test that.

**Comment by mrbuddhu** [comment]
[ERR] error while installing interactsh-server: could not find release asset for your platform (darwin/amd64) fauiled for M1 mac too

**Comment by ayadim** [comment]
Same thing happen to me in kali linux 
`┌──(kali㉿kali)-[~]
└─$ pdtm -i interactsh-client -v

                ____          
     ____  ____/ / /_____ ___ 
    / __ \/ __  / __/ __ __  \
   / /_/ / /_/ / /_/ / / / / /
  / .___/\__,_/\__/_/ /_/ /_/ 
 /_/                          v0.0.3

                projectdiscovery.io

[VER] using path /home/kali/.pdtm/go/bin
[INF] installing interactsh-client...
[ERR] error while installing interactsh-client: could not find release asset for your platform (linux/amd64)`

**Comment by ehsandeep** [comment]
@olearycrew this seems to be working as expected as there is no binary published for `amd*` arch for interactsh project as we can confirm from the [release](https://github.com/projectdiscovery/interactsh/releases) page.

**Comment by olearycrew** [comment]
@ehsandeep Ah my bad - I saw `arm` and read it as `amd`

**Comment by Mzack9999** [comment]
related #51

**Comment by Mzack9999** [comment]
Fixed with https://github.com/projectdiscovery/interactsh/pull/445

**Comment by Code-L0V3R** [comment]
```
pdtm -u interactsh-client

                ____          
     ____  ____/ / /_____ ___ 
    / __ \/ __  / __/ __ __  \
   / /_/ / /_/ / /_/ / / / / /
  / .___/\__,_/\__/_/ /_/ /_/ 
 /_/                          v0.0.3

		projectdiscovery.io

[INF] interactsh-client: not found
[INF] installing interactsh-client...
[ERR] error while updating interactsh-client: could not find release asset for your platform (linux/amd64)
```
do we need to wait until next release of interactsh ?

**Comment by ehsandeep** [comment]
> ```
> pdtm -u interactsh-client
> 
>                 ____          
>      ____  ____/ / /_____ ___ 
>     / __ \/ __  / __/ __ __  \
>    / /_/ / /_/ / /_/ / / / / /
>   / .___/\__,_/\__/_/ /_/ /_/ 
>  /_/                          v0.0.3
> 
> 		projectdiscovery.io
> 
> [INF] interactsh-client: not found
> [INF] installing interactsh-client...
> [ERR] error while updating interactsh-client: could not find release asset for your platform (linux/amd64)
> ```
> 
> do we need to wait until next release of interactsh ?

@Code-L0V3R Yes, changes will be reflected after next release of interactsh project.
