### ISSUE TITLE
Does not properly check latest version.

### ISSUE THREAD

**Issue by ransomsec** [projectdiscovery/pdtm#71]
### pdtm version:
Current Version: v0.0.3

### Current Behavior:
Does not properly check the latest version.

### Expected Behavior:
Check the latest version, and set old binary to outdated.

### Steps To Reproduce:
1. Run 'pdtm'
2. Output -> httpx (latest) (1.2.6) 
 | But the latest version is: (1.2.7)

### Anything else:
Screenshot

![issue](https://user-images.githubusercontent.com/83533000/218100701-6aeaaabb-1bc0-4916-8ec3-de46368f30fb.jpg)

**Comment by ehsandeep** [comment]
@ransomsec this should be fixed now, can you confirm?
