### ISSUE TITLE
Cannot install naabu

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/pdtm#84]
### pdtm version:
`v0.0.3`

### Current Behavior:
Unable to install naabu on `linux/amd64` with PDTM

### Expected Behavior:
Installs correctly

### Steps To Reproduce:
1. On a `linux/amd64` system, run `pdtm -i naabu`
2. Get the error

```
[ERR] error while installing naabu: could not find release asset for your platform (linux/amd64)
```

### Anything else:
<img width="1507" alt="CleanShot 2023-03-01 at 09 57 47@2x" src="https://user-images.githubusercontent.com/6044920/222176982-4770a173-021a-4636-a481-a24d9430b086.png">

**Comment by olearycrew** [comment]
Of note, `go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest` does work and then that install is detected by PDTM

**Comment by ehsandeep** [comment]
@olearycrew can you retry with latest version of pdtm?

**Comment by olearycrew** [comment]
@ehsandeep I cannot reproduce the issue on 0.0.3 or 0.0.4 now

**Comment by ehsandeep** [comment]
Closing this as of now as this is not reproducible, can be reopened in the future.
