### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by NezHacker** [projectdiscovery/pdtm#85]
![image](https://user-images.githubusercontent.com/87883732/222341895-3c2fd4e7-9dfa-4dfe-bfd0-0f0def0c54f0.png)

**Comment by ehsandeep** [comment]
@NezHacker should be resolved by now?

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/katana/discussions/339?converting=1#discussioncomment-5201405

**Comment by NezHacker** [comment]
> 

Yes, it's working properly
