### ISSUE TITLE
Missing assets for httpx in pdtm API

### ISSUE THREAD

**Issue by ggranjus** [projectdiscovery/pdtm#96]
### pdtm version: 

 v0.0.4

### Current Behavior:

<img width="698" alt="Screenshot 2023-03-15 at 11 57 03" src="https://user-images.githubusercontent.com/4239989/225289135-fbdef43d-9bff-4b20-9bad-c1cbbf5f8f58.png">

### Expected Behavior:

httpx should be installed.

### Steps To Reproduce:

1. Run `pdtm -i httpx`

### Anything else:

Assets for httpx are missing in pdtm API but are [present in httpx's repository](https://github.com/projectdiscovery/httpx/releases).
<img width="496" alt="Screenshot 2023-03-15 at 11 59 49" src="https://user-images.githubusercontent.com/4239989/225289774-727a209d-dc95-4ac3-ac89-d260cc25fd9a.png">

**Comment by ehsandeep** [comment]
@ggranjus thank you, it was cache issue, should be fixed now.
