### ISSUE TITLE
Asset for tlsx not found in Github API

### ISSUE THREAD

**Issue by ggranjus** [projectdiscovery/pdtm#97]
### pdtm version:

v0.0.4

### Current Behavior:

<img width="932" alt="Screenshot 2023-03-15 at 12 10 01" src="https://user-images.githubusercontent.com/4239989/225292073-b3d6b1a2-6a72-419b-88c7-2adc240720f3.png">

### Expected Behavior:

tlsx should be installed.

### Steps To Reproduce:

1. Run `pdtm -i tlsx`

### Anything else:

Asset is present in pdtm API but not in [tlsx repository for version 1.06](https://github.com/projectdiscovery/tlsx/releases).
<img width="489" alt="Screenshot 2023-03-15 at 12 11 27" src="https://user-images.githubusercontent.com/4239989/225292377-4df79d62-d89b-462e-b2e4-3d4c48ac3914.png">

**Comment by ehsandeep** [comment]
Fixed - https://github.com/projectdiscovery/tlsx/releases/tag/v1.0.6
